name: Build Question Data
on:
  workflow_dispatch:
    inputs:
        release:
            description: 'Release version'
            type: boolean
            required: false
            default: false

permissions:
  contents: write # Required to create releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Execute Gradle build
        run: ./gradlew ProcessHtml

      - name: Validate data
        run: ./gradlew ValidateJson

      - name: Upload data
        uses: actions/upload-artifact@v4
        with:
            name: question-data
            path: "build/questions"

      - name: Get current date
        id: date
        if: inputs.release
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Release
        uses: softprops/action-gh-release@v2
        if: inputs.release
        with:
          tag_name: ${{ steps.date.outputs.date }}
          name: ${{ steps.date.outputs.date }}
          files: "build/questions/*"
